### ISSUE TITLE
Can't create db.

### ISSUE THREAD

**Issue by Nexeonenn** [Maxime48/gmod-dayz#1]
![](https://media.discordapp.net/attachments/981981255178530866/982067244332900383/unknown.png?width=843&height=159)
I've tried everything and I don't understand why it doesn't work.
The database is working, mysql dll installed.

**Comment by Maxime48** [comment]
This does not seem to be an issue with your database configuration.
It seems that the gamemode is trying to add a player that does not exists to the database (because he is dead or has not spawned), but i do not have time to currently fix this bug and this isn't my gamemode.

I will leave this issue opened and fix this someday.
